name: morl-diff
channels:
  - conda-forge
  - defaults
  - pip:
    - absl-py==1.2.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - async-timeout==4.0.2
    - attrs==22.1.0
    - beautifulsoup4==4.11.1
    - boto3==1.24.59
    - botocore==1.27.59
    - cachetools==5.2.0
    - cffi==1.15.1
    - charset-normalizer==2.1.1
    - click==8.1.3
    - cloudpickle==1.6.0
    - configargparse==1.5.3
    - cycler==0.11.0
    - cython==0.29.32
    - d4rl==1.1
    - dm-control==1.0.5
    - dm-env==1.5
    - dm-tree==0.1.7
    - docker-pycreds==0.4.0
    - fasteners==0.17.3
    - filelock==3.8.0
    - fonttools==4.37.1
    - frozenlist==1.3.1
    - fsspec==2022.7.1
    - future==0.18.2
    - gdown==4.5.1
    - gitdb==4.0.9
    - gitpython==3.1.27
    - glfw==2.5.4
    - google-auth==2.11.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.47.0
    - gym==0.21.0
    - h5py==3.7.0
    - huggingface-hub==0.9.0
    - idna==3.3
    - imageio==2.9.0
    - jmespath==1.0.1
    - joblib==1.1.0
    - kiwisolver==1.4.4
    - labmaze==1.0.5
    - lxml==4.9.1
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.5.3
    - mjrl==1.0.0
    - mujoco==2.2.1
    - mujoco-py==2.1.2.14
    - multidict==6.0.2
    - oauthlib==3.2.0
    - pandas==1.4.3
    - pathtools==0.1.2
    - pillow==8.2.0
    - pip==22.3
    - promise==2.3
    - protobuf==3.19.4
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.21
    - pydeprecate==0.3.2
    - pyglet==1.5.15
    - pyopengl==3.1.6
    - pyparsing==2.4.7
    - pysocks==1.7.1
    - pytorch-lightning==1.7.3
    - pytorch-transformers==1.2.0
    - pytz==2022.2.1
    - pyyaml==6.0
    - regex==2022.8.17
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - s3transfer==0.6.0
    - sacremoses==0.0.53
    - scikit-learn==1.1.2
    - scipy==1.9.0
    - seaborn==0.11.2
    - sentencepiece==0.1.97
    - sentry-sdk==1.9.5
    - setproctitle==1.3.2
    - shortuuid==1.0.9
    - sklearn==0.0
    - smmap==5.0.0
    - soupsieve==2.3.2.post1
    - stable-baselines3==1.2.0
    - tensorboard==2.10.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - termcolor==1.1.0
    - threadpoolctl==3.1.0
    - tokenizers==0.10.3
    - torch==1.11.0+cu115
    - torchaudio==0.11.0+cu115
    - torchmetrics==0.9.3
    - torchvision==0.12.0+cu115
    - tqdm==4.64.0
    - transformers==4.5.1
    - typing-extensions==4.3.0
    - urllib3==1.26.12
    - wandb==0.13.2
    - werkzeug==2.2.2
    - yarl==1.8.1
