# reward_cat vs. rtg_cat
# CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/rtg_cat --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type dd --num_steps_per_iter 20000 --max_iters 2 --use_p_bar True --K 32 --n_diffusion_steps 2 &
# CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/rtg_cat --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type dd --num_steps_per_iter 20000 --max_iters 2 --use_p_bar True --K 32 --n_diffusion_steps 2 --returns_condition True &
# CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl/rtg_cat --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 20000 --max_iters 2 --use_p_bar True --K 32 --n_diffusion_steps 2 &
# CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl/rtg_cat --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 20000 --max_iters 2 --use_p_bar True --K 32 --n_diffusion_steps 2 --returns_condition True &
# wait

# bc diffusion step
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/finetune/diffussion_step/1 --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 20000 --max_iters 2 --use_p_bar True --K 32 --n_diffusion_steps 1 &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/finetune/diffussion_step/2 --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 20000 --max_iters 2 --use_p_bar True --K 32 --n_diffusion_steps 2 &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/finetune/diffussion_step/4 --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 20000 --max_iters 2 --use_p_bar True --K 32 --n_diffusion_steps 4 &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl/finetune/diffussion_step/8 --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 20000 --max_iters 2 --use_p_bar True --K 32 --n_diffusion_steps 8 &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl/finetune/diffussion_step/16 --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 20000 --max_iters 2 --use_p_bar True --K 32 --n_diffusion_steps 16 &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl/finetune/diffussion_step/32 --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 20000 --max_iters 2 --use_p_bar True --K 32 --n_diffusion_steps 32 &
wait

# dt diffusion step
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/finetune/diffussion_step/1 --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 20000 --max_iters 2 --use_p_bar True --K 32 --n_diffusion_steps 1 &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/finetune/diffussion_step/2 --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 20000 --max_iters 2 --use_p_bar True --K 32 --n_diffusion_steps 2 &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl/finetune/diffussion_step/4 --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 20000 --max_iters 2 --use_p_bar True --K 32 --n_diffusion_steps 4 &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl/finetune/diffussion_step/8 --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 20000 --max_iters 2 --use_p_bar True --K 32 --n_diffusion_steps 8 &
wait

CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/finetune/diffussion_step/1 --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 2 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 20000 --max_iters 2 --use_p_bar True --K 32 --n_diffusion_steps 1 &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/finetune/diffussion_step/2 --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 2 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 20000 --max_iters 2 --use_p_bar True --K 32 --n_diffusion_steps 2 &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/finetune/diffussion_step/3 --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 20000 --max_iters 2 --use_p_bar True --K 32 --n_diffusion_steps 3 &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl/finetune/diffussion_step/5 --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 20000 --max_iters 2 --use_p_bar True --K 32 --n_diffusion_steps 5 &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl/finetune/diffussion_step/6 --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 20000 --max_iters 2 --use_p_bar True --K 32 --n_diffusion_steps 6 &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl/finetune/diffussion_step/7 --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 20000 --max_iters 2 --use_p_bar True --K 32 --n_diffusion_steps 7 &
wait

# training step
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/finetune/train_step --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 100000 --max_iters 10 --use_p_bar True --K 32 --n_diffusion_steps 4 &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/finetune/train_step --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 100000 --max_iters 10 --use_p_bar True --K 32 --n_diffusion_steps 4 &
wait

# effect on expert custom
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl/finetune/effect --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl/finetune/effect --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 8 &
wait

# (weighted) returns condition 
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/finetune/return_cond --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/finetune/return_cond --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
wait
# *** NOTE then continued training on it and get 'return_cond1'

# guidance weight dt
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/finetune/cfg_w/0.5 --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --v_cfg_w 0.5 &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/finetune/cfg_w/0.8 --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --v_cfg_w 0.8 &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/finetune/cfg_w/1.0 --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --v_cfg_w 1.0 &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl/finetune/cfg_w/2.0 --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --v_cfg_w 2.0 &
wait

# guidance weight bc
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/finetune/bc_cfg_w/0.2 --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 100000 --max_iters 4 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --v_cfg_w 0.2 &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/finetune/bc_cfg_w/0.4 --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 100000 --max_iters 4 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --v_cfg_w 0.4 &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl/finetune/bc_cfg_w/0.6 --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 100000 --max_iters 4 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --v_cfg_w 0.6 &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl/finetune/bc_cfg_w/0.8 --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 100000 --max_iters 4 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --v_cfg_w 0.8 &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl/finetune/bc_cfg_w/1.0 --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 100000 --max_iters 4 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --v_cfg_w 1.0 &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl/finetune/bc_cfg_w/2.0 --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 100000 --max_iters 4 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --v_cfg_w 2.0 &
wait

CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/finetune/bc_cfg_w/0.1 --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 100000 --max_iters 4 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --v_cfg_w 0.1 &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/finetune/bc_cfg_w/0.7 --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 100000 --max_iters 4 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --v_cfg_w 0.7 &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/finetune/bc_cfg_w/0.75 --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 100000 --max_iters 4 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --v_cfg_w 0.75 &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/finetune/bc_cfg_w/0.85 --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 100000 --max_iters 4 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --v_cfg_w 0.85 &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl/finetune/bc_cfg_w/0.9 --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 100000 --max_iters 4 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --v_cfg_w 0.9 &
wait

## bc, dd, dt; swimmer 10000
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/finetune/rtg_cat --env MO-Swimmer-v2 --num_traj 10000 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type dd --num_steps_per_iter 10000 --max_iters 4 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --v_cfg_w 0.8 &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl/finetune/rtg_cat --env MO-Swimmer-v2 --num_traj 10000 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 10000 --max_iters 4 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --v_cfg_w 0.8 &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl/finetune/rtg_cat --env MO-Swimmer-v2 --num_traj 10000 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 10000 --max_iters 4 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --v_cfg_w 0.8 &
wait

## bc, dd, dt; swimmer 10000
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl/finetune/rtg_cat_norm --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type dd --num_steps_per_iter 20000 --max_iters 4 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl/finetune/rtg_cat_norm --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 20000 --max_iters 4 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl/finetune/rtg_cat_norm --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 20000 --max_iters 4 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
wait

# scale == 1 !
# bc dd, dt; ant 40000x5
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/finetune/rtg_cat_norm --env MO-Ant-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type dd --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 64 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/finetune/rtg_cat_norm --env MO-Ant-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 64 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/finetune/rtg_cat_norm --env MO-Ant-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 64 --n_diffusion_steps 1 --returns_condition True &
wait

CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl/finetune/rtg_cat --env MO-Ant-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type dd --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 64 --n_diffusion_steps 2 --returns_condition True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl/finetune/rtg_cat --env MO-Ant-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 64 --n_diffusion_steps 2 --returns_condition True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl/finetune/rtg_cat --env MO-Ant-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 64 --n_diffusion_steps 2 --returns_condition True &
wait

# normalized, modified evaluator (target_return -> target_reward)
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/finetune/reward_cat --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type dd --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --normalize_reward True &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/finetune/reward_cat --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --normalize_reward True &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/finetune/reward_cat --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --normalize_reward True &
wait

# K==16(for swimmer) # normalized, modified evaluator (target_return -> target_reward)
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/finetune/reward_cat --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 2 --dataset expert_uniform --model_type mod --mod_type dd --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 16 --n_diffusion_steps 1 --returns_condition True --normalize_reward True &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/finetune/reward_cat --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 2 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 16 --n_diffusion_steps 1 --returns_condition True --normalize_reward True &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/finetune/reward_cat --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 2 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 16 --n_diffusion_steps 1 --returns_condition True --normalize_reward True &
wait

# condition on reward and infer with ones reward, normalized reward
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl/finetune/target_r --env MO-Ant-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type dd --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --normalize_reward True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl/finetune/target_r --env MO-Ant-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --normalize_reward True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl/finetune/target_r --env MO-Ant-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --normalize_reward True &
wait

CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/finetune/target_r --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type dd --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 16 --n_diffusion_steps 1 --returns_condition True --normalize_reward True &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/finetune/target_r --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 16 --n_diffusion_steps 1 --returns_condition True --normalize_reward True &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/finetune/target_r --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 16 --n_diffusion_steps 1 --returns_condition True --normalize_reward True &
wait

# only last reward==ones
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/finetune/target_r1 --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 101 --dataset expert_uniform --model_type mod --mod_type dd --num_steps_per_iter 100000 --max_iters 10 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --normalize_reward True &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/finetune/target_r1 --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 101 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 100000 --max_iters 10 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --normalize_reward True &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/finetune/target_r1 --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 101 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 100000 --max_iters 10 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --normalize_reward True &
wait

# all bc
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/all --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 200000 --max_iters 2 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --normalize_reward True &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/all --env MO-Ant-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 200000 --max_iters 2 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --normalize_reward True &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/all --env MO-Hopper-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 200000 --max_iters 2 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --normalize_reward True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl/all --env MO-Hopper-v3 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 200000 --max_iters 2 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --normalize_reward True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl/all --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 200000 --max_iters 2 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --normalize_reward True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl/all --env MO-Walker2d-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 200000 --max_iters 2 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --normalize_reward True &
wait

# all dt
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/all --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 200000 --max_iters 2 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --normalize_reward True &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/all --env MO-Ant-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 200000 --max_iters 2 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --normalize_reward True &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/all --env MO-Hopper-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 200000 --max_iters 2 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --normalize_reward True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl/all --env MO-Hopper-v3 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 200000 --max_iters 2 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --normalize_reward True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl/all --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 200000 --max_iters 2 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --normalize_reward True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl/all --env MO-Walker2d-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 200000 --max_iters 2 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --normalize_reward True &
wait

# concat all + cfg weighted returns
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/finetune/cat_all --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 2 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --normalize_reward True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl/finetune/cat_all --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 2 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --normalize_reward True &
wait

# concat all + cfg unweighted returns
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/finetune/cat_all --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 3 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --normalize_reward True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl/finetune/cat_all --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 3 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --normalize_reward True &
wait
# *** unweighted returns on mod-bc degrade pref achievements

# concat all + cfg (un)weighted returns + dt + diffusion step
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/finetune/cat_all2 --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 3 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 2 --returns_condition True --normalize_reward True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl/finetune/cat_all3 --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 3 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 3 --returns_condition True --normalize_reward True &
wait
# weighted
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/finetune/cat_all3/ds4 --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 3 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 4 --returns_condition True --normalize_reward True &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/finetune/cat_all3/ds8 --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 3 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 8 --returns_condition True --normalize_reward True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl/finetune/cat_all3/ds12 --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 3 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 12 --returns_condition True --normalize_reward True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl/finetune/cat_all3/ds16 --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 3 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 16 --returns_condition True --normalize_reward True &
wait
# *** no improvement to ds==1

# other normalization
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/norm_other --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type dt --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --normalize_reward True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl/norm_other --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type bc --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --normalize_reward True &
wait
# *** normalizing harms baselines !

# max guidance using max_reward rather than normalized and do that using 1
# all no_norm
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/no_norm --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/no_norm --env MO-Ant-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/no_norm --env MO-Hopper-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl/no_norm --env MO-Hopper-v3 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl/no_norm --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl/no_norm --env MO-Walker2d-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
wait

# all dt
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/no_norm --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/no_norm --env MO-Ant-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl/no_norm --env MO-Hopper-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl/no_norm --env MO-Hopper-v3 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl/no_norm --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl/no_norm --env MO-Walker2d-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
wait
# *** mod-dt is slightly better than mod-bc

### what to concat
# dt with r or g
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl1/concat_on_r --env MO-Hopper-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 80000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --concat_on r &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl1/concat_on_r --env MO-Walker2d-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 80000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --concat_on r &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl1/concat_on_g --env MO-Hopper-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 80000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --concat_on g &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl1/concat_on_g --env MO-Walker2d-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 80000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --concat_on g &
wait
# *** concat on r is better

### batch_size
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl1/batch_size/32 --env MO-Swimmer-v2 --batch_size 32 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl1/batch_size/128 --env MO-Swimmer-v2 --batch_size 128 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl1/batch_size/256 --env MO-Swimmer-v2 --batch_size 256 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl1/batch_size/1024 --env MO-Swimmer-v2 --batch_size 1024 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl1/batch_size/32 --env MO-Swimmer-v2 --batch_size 32 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl1/batch_size/128 --env MO-Swimmer-v2 --batch_size 128 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl1/batch_size/256 --env MO-Swimmer-v2 --batch_size 256 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl1/batch_size/1024 --env MO-Swimmer-v2 --batch_size 1024 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
wait
# *** bc: 64 with larger train_step or larger learning_rate; dt: 32~256

### learning rate
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl1/learning_rate/5e-5 --env MO-Swimmer-v2 --learning_rate 5e-5 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl1/learning_rate/1e-4 --env MO-Swimmer-v2 --learning_rate 1e-4 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl1/learning_rate/2e-4 --env MO-Swimmer-v2 --learning_rate 2e-4 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl1/learning_rate/5e-4 --env MO-Swimmer-v2 --learning_rate 5e-4 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl1/learning_rate/1e-3 --env MO-Swimmer-v2 --learning_rate 1e-3 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl1/learning_rate/2e-3 --env MO-Swimmer-v2 --learning_rate 2e-3 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
wait
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl1/learning_rate/5e-5 --env MO-Swimmer-v2 --learning_rate 5e-5 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl1/learning_rate/1e-4 --env MO-Swimmer-v2 --learning_rate 1e-4 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl1/learning_rate/2e-4 --env MO-Swimmer-v2 --learning_rate 2e-4 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl1/learning_rate/5e-4 --env MO-Swimmer-v2 --learning_rate 5e-4 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl1/learning_rate/1e-3 --env MO-Swimmer-v2 --learning_rate 1e-3 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl1/learning_rate/2e-3 --env MO-Swimmer-v2 --learning_rate 2e-3 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
wait
# *** bc: 2e-3 better ach and hv; dt: 1e-4 or 2e-4

# adam and adamW
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl1/opt/adam --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True
# --- modify the opt type
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl1/opt/adamw --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True
# *** some improvement

# adamW and sche
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl1/sche --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True
# *** a bit of improvement

# warmup_steps
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl1/warmup_steps/10000 --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --warmup_steps 10000 &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl1/warmup_steps/20000 --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --warmup_steps 20000 &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl1/warmup_steps/50000 --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --warmup_steps 50000 &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl1/warmup_steps/100000 --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --warmup_steps 100000 &
wait
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl1/warmup_steps/10000 --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --warmup_steps 10000 &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl1/warmup_steps/20000 --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --warmup_steps 20000 &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl1/warmup_steps/50000 --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --warmup_steps 50000 &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl1/warmup_steps/100000 --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --warmup_steps 100000 &
wait
# *** bc:20000, dt:10000

# combine the above
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl1/comb --env MO-HalfCheetah-v2 --learning_rate 2e-3 --batch_size 32 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 40000 --max_iters 20 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl1/comb --env MO-Hopper-v2 --learning_rate 2e-3 --batch_size 32 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 40000 --max_iters 20 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl1/comb --env MO-Walker2d-v2 --learning_rate 2e-3 --batch_size 32 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 40000 --max_iters 20 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl1/comb --env MO-Swimmer-v2 --learning_rate 2e-3 --batch_size 32 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 40000 --max_iters 20 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl1/comb --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 20 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl1/comb --env MO-Hopper-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 20 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl1/comb --env MO-Walker2d-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 20 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl1/comb --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 20 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
wait
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl1/comb --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dd --num_steps_per_iter 40000 --max_iters 20 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl1/comb --env MO-Hopper-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dd --num_steps_per_iter 40000 --max_iters 20 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl1/comb --env MO-Walker2d-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dd --num_steps_per_iter 40000 --max_iters 20 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl1/comb --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dd --num_steps_per_iter 40000 --max_iters 20 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
wait

# more diffusion step ?
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl1/diff_step10 --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 80000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 10 --returns_condition True &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl1/diff_step10 --env MO-Hopper-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 80000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 10 --returns_condition True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl1/diff_step10 --env MO-Walker2d-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 80000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 10 --returns_condition True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl1/diff_step10 --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 80000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 10 --returns_condition True &
wait

# eval only
# experiment_runs/mod_impl/finetune/return_cond1/mod/normal/bc/MO-HalfCheetah-v2/expert_uniform/1/ckpt/step=160000.ckpt
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl1/eval_only --eval_only True --ckpt experiment_runs/mod_impl/finetune/return_cond1/mod/normal/bc/MO-HalfCheetah-v2/expert_uniform/1/ckpt/step=160000.ckpt --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 80000 --max_iters 5 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &

# comb, all (REVERT)
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl2/comb --env MO-Ant-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 100000 --max_iters 4 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl2/comb --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 100000 --max_iters 4 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl2/comb --env MO-Hopper-v3 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 100000 --max_iters 4 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --granularity 50 &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl2/comb --env MO-Ant-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 100000 --max_iters 4 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl2/comb --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 100000 --max_iters 4 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl2/comb --env MO-Hopper-v3 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 100000 --max_iters 4 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl2/comb --env MO-Hopper-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 100000 --max_iters 4 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl2/comb --env MO-Walker2d-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 100000 --max_iters 4 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl2/comb --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 100000 --max_iters 4 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl2/comb --env MO-Hopper-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 100000 --max_iters 4 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl2/comb --env MO-Walker2d-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 100000 --max_iters 4 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl2/comb --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 100000 --max_iters 4 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True &
wait

CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl2/comb --env MO-Hopper-v3 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 100000 --max_iters 4 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --granularity 50 &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl2/comb --env MO-Hopper-v3 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 100000 --max_iters 4 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --granularity 50 &
wait

# data synthesis
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/syn --env MO-Swimmer-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 20 --max_iters 1 --use_p_bar True --K 256 --n_diffusion_steps 100 --returns_condition True --granularity 2 --collect True --collect_num 10000

CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/debug --env MO-Hopper-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 100000 --max_iters 4 --use_p_bar True --K 32 --n_diffusion_steps 1 --returns_condition True --granularity 50

# cur_R
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl2/cur_r64 --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 100000 --max_iters 4 --use_p_bar True --K 32 --n_diffusion_steps 8 --returns_condition True --granularity 100 &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl2/cur_r64 --env MO-Hopper-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 100000 --max_iters 4 --use_p_bar True --K 32 --n_diffusion_steps 8 --returns_condition True --granularity 100 &
wait

# no action inpaint conditioning
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl2/no_act_cond --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 4 --use_p_bar True --K 32 --infer_N 31 --n_diffusion_steps 8 --returns_condition True --granularity 100 &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl2/no_act_cond --env MO-Hopper-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 4 --use_p_bar True --K 32 --infer_N 31 --n_diffusion_steps 8 --returns_condition True --granularity 100 &
wait
# *** dont use this, can use 'no reward/rtg inpainting'

CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl2/check --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 8 --n_diffusion_steps 8 --returns_condition True --granularity 100 &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl2/check --env MO-Hopper-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 8 --n_diffusion_steps 16 --returns_condition True --granularity 100 &
wait
# *** OK

# pref as hard cond
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl2/hard_pref --env MO-HalfCheetah-v2 --concat_state_pref 0 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 8 --n_diffusion_steps 8 --returns_condition True --granularity 100 &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl2/hard_pref --env MO-Hopper-v2 --concat_state_pref 0 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 8 --n_diffusion_steps 8 --returns_condition True --granularity 200 &
wait
# *** OK

# hard pref and ---plan---
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl2/hard_pref2 --env MO-HalfCheetah-v2 --concat_state_pref 0 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 8 --infer_N 4 --n_diffusion_steps 8 --returns_condition True --granularity 100 &
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl2/hard_pref2 --env MO-Hopper-v2 --concat_state_pref 0 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 40000 --max_iters 5 --use_p_bar True --K 8 --infer_N 4 --n_diffusion_steps 8 --returns_condition True --granularity 200 &
wait
# *** issuing on ---plan--- and ---pref ach---

# longer train
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl2/hard_pref2 --env MO-HalfCheetah-v2 --concat_state_pref 0 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 50000 --max_iters 20 --use_p_bar True --K 8 --infer_N 7 --n_diffusion_steps 16 --returns_condition True --granularity 10 &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl2/hard_pref2 --env MO-Hopper-v2 --concat_state_pref 0 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 50000 --max_iters 20 --use_p_bar True --K 8 --infer_N 7 --n_diffusion_steps 16 --returns_condition True --granularity 50 &
wait
# *** bad

# longer train w/ larger guidance scale (condition more on target_return)
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl2/hard_pref3 --env MO-HalfCheetah-v2 --concat_state_pref 0 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 50000 --max_iters 20 --use_p_bar True --K 8 --infer_N 7 --n_diffusion_steps 16 --returns_condition True --granularity 10 --v_cfg_w 2 &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl2/hard_pref3 --env MO-Hopper-v2 --concat_state_pref 0 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 50000 --max_iters 20 --use_p_bar True --K 8 --infer_N 7 --n_diffusion_steps 16 --returns_condition True --granularity 50 --v_cfg_w 2 &
wait
# *** bad

# l1 loss
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl2/loss-l1 --env MO-HalfCheetah-v2 --concat_state_pref 0 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 50000 --max_iters 4 --use_p_bar True --K 8 --infer_N 4 --n_diffusion_steps 16 --returns_condition True --granularity 50 &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl2/loss-l1 --env MO-Hopper-v2 --concat_state_pref 0 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 50000 --max_iters 4 --use_p_bar True --K 8 --infer_N 4 --n_diffusion_steps 16 --returns_condition True --granularity 50 &
wait
# *** no influence

# concat weighted r
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl2/weighted_r/4 --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 50000 --max_iters 4 --use_p_bar True --K 8 --infer_N 4 --n_diffusion_steps 16 --returns_condition True --granularity 50 &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl2/weighted_r/0 --env MO-HalfCheetah-v2 --concat_state_pref 1 --concat_rtg_pref 1 --concat_act_pref 1 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 50000 --max_iters 4 --use_p_bar True --K 8 --infer_N 0 --n_diffusion_steps 16 --returns_condition True --granularity 50 &
wait

# planning
CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl2/plan --env MO-HalfCheetah-v2 --concat_state_pref 0 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 50000 --max_iters 20 --use_p_bar True --K 8 --infer_N 7 --n_diffusion_steps 16 --returns_condition True --granularity 50 &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl2/plan --env MO-Hopper-v2 --concat_state_pref 0 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type bc --num_steps_per_iter 50000 --max_iters 20 --use_p_bar True --K 8 --infer_N 7 --n_diffusion_steps 16 --returns_condition True --granularity 50 &
wait

CUDA_VISIBLE_DEVICES=1 python experiment.py --dir experiment_runs/mod_impl2/plan --env MO-HalfCheetah-v2 --concat_state_pref 0 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 50000 --max_iters 20 --use_p_bar True --K 8 --infer_N 7 --n_diffusion_steps 16 --returns_condition True --granularity 50 &
CUDA_VISIBLE_DEVICES=0 python experiment.py --dir experiment_runs/mod_impl2/plan --env MO-Hopper-v2 --concat_state_pref 0 --concat_rtg_pref 0 --concat_act_pref 0 --seed 1 --dataset expert_uniform --model_type mod --mod_type dt --num_steps_per_iter 50000 --max_iters 20 --use_p_bar True --K 8 --infer_N 7 --n_diffusion_steps 16 --returns_condition True --granularity 50 &
wait